### ISSUE TITLE
Calculation fails on 0 value for RROE

### ISSUE THREAD

**Issue by RosenvingeDK** [microsoft/AzureDevOps-WSJF-Extension#13]
Currently if the value in RROE is 0 the entire value of WSJF is set to 0 which doesn't jive with the supposed function of Business Value + Time Criticality + RROE.

**Comment by bchase-humana** [comment]
We are using Azure DevOps Services and specifically the Agile Process template (inherited). We had to create a new field called RR-OE. We set that decimal field to hidden. Then created a rule that said if the Risk field (text) was (1 - High) then  set RR-OE value to 1, and similarly for "2 - Medium" and "3 - Low".  Selecting risk 1, 2, 3 becomes part of the input. You can't use Risk directly because it is a text field not decimal.
